baseURL = 'https://devfest26.gdgvenezia.it/'
languageCode = 'en'
theme = "devfest-hugo-theme"
title = 'DevFest Venezia 26'

[pagination]
  pagerSize = 6

# Main Menu
[[menu.main]]
name = "Agenda"
pageRef = "/agenda"
weight = 1
[[menu.main]]
name = "Speakers"
pageRef = "/speakers"
weight = 2
[[menu.main]]
name = "Sponsors"
url = "/#sponsors"
weight = 3
[[menu.main]]
name = "Venue"
url = "/#venue"
weight = 4
[[menu.main]]
name = "Past editions"
pageRef = "/gallery"
weight = 5

[params]
  description = "DevFest Venezia 2026 - 24 October - Venezia"
  copyright = "© {year} <a href=\"https://marcogomiero.com/\" target=\"_blank\">Marco Gomiero </a>"
  googleAnalytics = ""
  logo = "images/logo.webp"
  footerDescription = "Organized by <a href=\"https://gdg.community.dev/gdg-venezia/\" target=\"BLANK\">Google Developer Group Venezia</a>."

  [params.location]
  title = "Location"

  [params.location.venezia]
  address = "Campus Scientifico Università Ca' Foscari"
  desc = "Via Torino, 155 Mestre, Venezia VE, 30170"
  mapsLink = "https://www.google.com/maps/dir//Via%20Torino%2C%20155%20Mestre%2C%20Venezia%20VE"
